;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT LEVELNAME

LEVELNAME:
	.WORD background_index, spawn_stream
	.BYTE $00, $00 ; high byte of player starting X and Y
	.BYTE $01 ; length of background, zero based

background_index:
	.WORD background_0, background_1
spawn_stream:
	.WORD stream_0,stream_1

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $0A, $0C, $22, $0B, $FF, $01, $17, $2E, $FF, $00 
  .BYTE $0C, $0A, $5F, $52, $FF, $02, $03, $B2, $FD, $F0, $FF, $0F, $03, $BA, $FD, $30 
  .BYTE $33, $03, $08, $B5, $FC, $55, $55, $55, $05, $06, $D0, $FE, $C0, $0C, $04, $D8 
  .BYTE $FE, $F0, $0F, $04, $DE, $FE, $30, $03, $06, $D2, $FE, $00, $00, $00 

stream_0:

background_1:
  .BYTE $FF, $00, $08, $00, $FD, $02, $00, $01, $22, $00, $FF, $01, $2F, $23, $06, $22 
  .BYTE $05, $52, $04, $5D, $FF, $01, $05, $6D, $05, $67, $03, $71, $03, $51, $04, $72 
  .BYTE $06, $6F, $08, $83, $0E, $84, $05, $9D, $FE, $04, $04, $16, $99, $04, $94, $FC 
  .BYTE $01, $11, $11, $11, $0A, $53, $08, $CC, $FD, $44, $44, $44, $03, $D2, $FD, $55 
  .BYTE $55, $55, $09, $D8, $FE, $15, $51, $04, $E3, $03, $EC, $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00
