;
; neschael
; data/sound/tracks.s
;
; file generated by tools/formatSong.c
; music and sfx data
;

.INCLUDE "lib/sound/sound.inc"

.EXPORT song_list_low
.EXPORT song_list_high
.EXPORT sfx_list_low
.EXPORT sfx_list_high
.EXPORT instrument_list_low
.EXPORT instrument_list_high

song_list_low:
	.BYTE <_Song1
song_list_high:
	.BYTE >_Song1

sfx_list_low:
sfx_list_high:

instrument_list_low:
	.BYTE <_dru_0
	.BYTE <_Instrument_1_1
	.BYTE <silent_2
instrument_list_high:
	.BYTE >_dru_0
	.BYTE >_Instrument_1_1
	.BYTE >silent_2

_dru_0:
	.BYTE $05, $0C, $0E, $10, ARP_TYPE_ABSOLUTE
	.BYTE $0F, $0B, $07, $03, $01, $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Instrument_1_1:
	.BYTE $05, $07, $09, $0B, ARP_TYPE_ABSOLUTE
	.BYTE $0F, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

silent_2:
	.BYTE $05, $07, $09, $0B, ARP_TYPE_ABSOLUTE
	.BYTE $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Song1:
	.BYTE $00
	.BYTE $01
	.WORD _Song1_square1
	.WORD _Song1_square2
	.WORD $00
	.WORD _Song1_noise

_Song1_square1:
_Song1_square1_loop:
	.BYTE CAL,<(_Song1_square1_0),>(_Song1_square1_0)
	.BYTE CAL,<(_Song1_square1_1),>(_Song1_square1_1)
	.BYTE CAL,<(_Song1_square1_2),>(_Song1_square1_2)
	.BYTE CAL,<(_Song1_square1_1),>(_Song1_square1_1)
	.BYTE CAL,<(_Song1_square1_3),>(_Song1_square1_3)
	.BYTE CAL,<(_Song1_square1_4),>(_Song1_square1_4)
	.BYTE CAL,<(_Song1_square1_5),>(_Song1_square1_5)
	.BYTE GOT
	.WORD _Song1_square1_loop

_Song1_square2:
_Song1_square2_loop:
	.BYTE CAL,<(_Song1_square2_0),>(_Song1_square2_0)
	.BYTE CAL,<(_Song1_square2_0),>(_Song1_square2_0)
	.BYTE CAL,<(_Song1_square2_1),>(_Song1_square2_1)
	.BYTE CAL,<(_Song1_square2_2),>(_Song1_square2_2)
	.BYTE CAL,<(_Song1_square2_3),>(_Song1_square2_3)
	.BYTE CAL,<(_Song1_square2_0),>(_Song1_square2_0)
	.BYTE CAL,<(_Song1_square2_1),>(_Song1_square2_1)
	.BYTE GOT
	.WORD _Song1_square2_loop

_Song1_noise:
_Song1_noise_loop:
	.BYTE CAL,<(_Song1_noise_0),>(_Song1_noise_0)
	.BYTE CAL,<(_Song1_noise_1),>(_Song1_noise_1)
	.BYTE CAL,<(_Song1_noise_2),>(_Song1_noise_2)
	.BYTE CAL,<(_Song1_noise_1),>(_Song1_noise_1)
	.BYTE CAL,<(_Song1_noise_2),>(_Song1_noise_2)
	.BYTE CAL,<(_Song1_noise_1),>(_Song1_noise_1)
	.BYTE CAL,<(_Song1_noise_2),>(_Song1_noise_2)
	.BYTE GOT
	.WORD _Song1_noise_loop

_Song1_square1_0:
	.BYTE STI, $02, SLL,160, A0
	.BYTE RET

_Song1_square1_1:
	.BYTE STI, $01, SLA, CS4, SLL,30, GS4, SLL,40, DS4, AS4, SLA
	.BYTE GS4, AS4, F5, C4
	.BYTE RET

_Song1_square1_2:
	.BYTE STI, $01, SLL,20, GS4, F4, STI, $02, SLL,40, A0, STI, $01
	.BYTE SLL,20, GS4, F4, STI, $02, SLL,40, A0
	.BYTE RET

_Song1_square1_3:
	.BYTE STI, $01, SLL,20, C5, GS4, STI, $02, SLL,40, A0, STI, $01
	.BYTE SLL,20, C5, GS4, STI, $02, SLL,40, A0
	.BYTE RET

_Song1_square1_4:
	.BYTE STI, $01, SLL,40, C5, GS4, DS5, SLA, AS4, C5, STI, $02
	.BYTE A0, STI, $01, F5
	.BYTE RET

_Song1_square1_5:
	.BYTE STI, $01, SLL,20, GS5, F5, STI, $02, SLL,40, A0, STI, $01
	.BYTE SLL,20, GS5, F5, STI, $02, SLL,40, A0
	.BYTE RET

_Song1_square2_0:
	.BYTE STI, $01, SLA, C4, AS3, F3, C4, AS3, F3, C4, AS3, F3, C4
	.BYTE AS3, F3, C4, AS3, F3, STI, $02, A0
	.BYTE RET

_Song1_square2_1:
	.BYTE STI, $01, SLA, C4, AS3, F3, C4, AS3, F3, C4, AS3, D4, C4
	.BYTE AS3, F3, C4, AS3, F4, STI, $02, A0
	.BYTE RET

_Song1_square2_2:
	.BYTE STI, $01, SLA, C4, AS3, F3, F4, C4, AS3, F3, F4, C4, AS3
	.BYTE DS3, C4, AS3, F3, C4, STI, $02, A0
	.BYTE RET

_Song1_square2_3:
	.BYTE STI, $01, SLA, F4, AS3, F3, F4, AS3, F3, F4, AS3, F3, F4
	.BYTE AS3, F3, F4, AS3, F3, STI, $02, A0
	.BYTE RET

_Song1_noise_0:
	.BYTE STI, $02, SLL,80, A0, STI, $00, SLL,20, $00, SLA, $0F
	.BYTE $07, STI, $02, SLL,20, A0, STI, $00, SLA, $07, STI, $02
	.BYTE A0
	.BYTE RET

_Song1_noise_1:
	.BYTE STI, $00, SLL,20, $00, SLA, $0F, $07, STI, $02, SLL,20
	.BYTE A0, STI, $00, SLA, $07, STI, $02, SLL,30, A0, STI, $00
	.BYTE SLA, $07, STI, $02, A0, STI, $00, SLL,20, $01, SLA, $07
	.BYTE STI, $02, A0
	.BYTE RET

_Song1_noise_2:
	.BYTE STI, $00, SLL,20, $00, SLA, $0F, $07, STI, $02, SLL,20
	.BYTE A0, STI, $00, SLA, $07, STI, $02, A0, STI, $00, SLL,20
	.BYTE $00, SLA, $0F, $07, STI, $02, SLL,20, A0, STI, $00
	.BYTE SLA, $07, STI, $02, A0
	.BYTE RET

