;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT LEVELNAME

LEVELNAME:
	.WORD background_index, spawn_stream
	.BYTE $00, $00 ; high byte of player starting X and Y
	.BYTE $03 ; length of background, zero based

background_index:
	.WORD background_0, background_1, background_2, background_3
spawn_stream:
	.WORD stream_0,stream_1,stream_2,stream_3

background_0:
  .BYTE $FF, $00, $06, $00, $FF, $01, $04, $07, $07, $00, $05, $06, $08, $0C, $04, $13 
  .BYTE $06, $1B, $FF, $02, $05, $1E, $06, $24, $FF, $03, $05, $1D, $06, $25, $0C, $36 
  .BYTE $06, $1C, $0A, $3D, $07, $52, $07, $1B, $10, $60, $07, $2F, $0A, $17, $11, $69 
  .BYTE $FE, $02, $01, $05, $94, $05, $21, $0A, $9E, $04, $8F, $09, $94, $FD, $F0, $FF 
  .BYTE $0F, $03, $BC, $FE, $30, $33, $06, $59, $03, $CE, $FC, $55, $55, $55, $05, $06 
  .BYTE $D0, $FE, $C0, $0C, $04, $D8, $FE, $F0, $0F, $04, $DE, $FE, $30, $03, $06, $D2 
  .BYTE $FE, $00, $00, $00 

stream_0:

background_1:
  .BYTE $FB, $01, $00, $00, $00, $02, $03, $01, $03, $07, $FF, $01, $03, $00, $FF, $02 
  .BYTE $04, $00, $1A, $08, $FF, $01, $21, $23, $FF, $02, $03, $46, $33, $48, $05, $86 
  .BYTE $0C, $80, $FD, $00, $03, $03, $0A, $8F, $06, $21, $15, $9F, $FD, $11, $11, $11 
  .BYTE $0B, $B4, $07, $CD, $FD, $44, $44, $44, $03, $D2, $FD, $55, $55, $55, $0F, $D8 
  .BYTE $03, $EC, $FE, $28, $08, $00 

stream_1:
	.BYTE $2B, $00, $00 ; X: 11, Y: 02
	.BYTE $73, $00, $00 ; X: 03, Y: 07
	.BYTE $65, $00, $00 ; X: 05, Y: 06
	.BYTE $00

background_2:
  .BYTE $FE, $01, $00, $09, $01, $FF, $01, $19, $00, $08, $18, $04, $23, $08, $25, $FE 
  .BYTE $03, $03, $0A, $2F, $03, $2B, $0D, $3C, $0B, $19, $22, $54, $1A, $0B, $0B, $3F 
  .BYTE $17, $9B, $03, $3A, $06, $C0, $FE, $50, $55, $0D, $C3, $FE, $A0, $AA, $04, $CF 
  .BYTE $08, $D6, $F8, $C0, $CC, $00, $00, $20, $22, $F0, $FF, $06, $B7, $00 

stream_2:
	.BYTE $28, $00, $00 ; X: 08, Y: 02
	.BYTE $00

background_3:
  .BYTE $FF, $00, $06, $00, $FE, $01, $01, $03, $05, $08, $00, $07, $10, $FD, $00, $00 
  .BYTE $02, $09, $0E, $1E, $1B, $FF, $02, $04, $07, $19, $3E, $FD, $02, $03, $03, $0A 
  .BYTE $5A, $06, $54, $0F, $6A, $FE, $04, $04, $16, $7B, $08, $9C, $0C, $99, $03, $06 
  .BYTE $0C, $B3, $FE, $F0, $FF, $0A, $A8, $FC, $00, $A0, $AA, $AA, $09, $CA, $FD, $20 
  .BYTE $22, $22, $0B, $C2, $03, $E6, $FF, $FF, $05, $EA, $FE, $0C, $00, $00 

stream_3:
	.BYTE $32, $00, $00 ; X: 02, Y: 03
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $00
