;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT LEVELNAME

LEVELNAME:
	.WORD background_index, spawn_stream
	.BYTE $00, $00 ; high byte of player starting X and Y
	.BYTE $01 ; ammount of backgrounds, zero based
	.BYTE $3F ; background color
	.BYTE $00, $01, $02, $03 ; background palettes
	.BYTE $00, $01, $02, $03 ; sprite palettes

background_index:
	.WORD background_0, background_1
spawn_stream:
	.WORD stream_0,stream_1

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $07, $0C, $FF, $06, $0B, $09, $04, $13, $09, $18 
  .BYTE $03, $20, $0A, $24, $FF, $00, $0B, $2F, $FF, $05, $0A, $3B, $FF, $05, $0A, $22 
  .BYTE $03, $51, $09, $53, $0C, $08, $FF, $09, $0B, $69, $FF, $0A, $09, $75, $FF, $07 
  .BYTE $05, $72, $06, $84, $FF, $08, $05, $7E, $06, $85, $04, $9B, $FF, $09, $06, $9B 
  .BYTE $FF, $08, $04, $A7, $FF, $0A, $05, $A7, $07, $51, $FB, $01, $00, $F0, $FF, $0F 
  .BYTE $03, $BC, $FD, $30, $33, $03, $08, $78, $FC, $55, $55, $55, $05, $06, $D0, $FE 
  .BYTE $C0, $0C, $04, $D8, $FE, $F0, $0F, $04, $DE, $FE, $30, $03, $06, $D2, $FE, $00 
  .BYTE $00, $00 

stream_0:

background_1:
  .BYTE $F9, $00, $00, $00, $05, $01, $01, $01, $03, $00, $FF, $07, $04, $06, $FF, $06 
  .BYTE $06, $04, $FF, $08, $04, $12, $04, $0E, $04, $08, $05, $17, $05, $27, $FF, $08 
  .BYTE $0A, $22, $03, $21, $09, $2F, $03, $2D, $09, $3B, $03, $45, $11, $47, $06, $5E 
  .BYTE $FE, $02, $01, $05, $5B, $05, $64, $FF, $02, $04, $70, $05, $76, $08, $5A, $11 
  .BYTE $7C, $06, $6D, $04, $9E, $FD, $04, $04, $0C, $15, $9A, $04, $94, $FC, $01, $11 
  .BYTE $11, $11, $0A, $23, $08, $CC, $FD, $44, $44, $44, $03, $D2, $FD, $55, $55, $55 
  .BYTE $09, $D8, $FE, $15, $51, $04, $E3, $03, $EC, $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00
