;
; neschael
; data/tiles/metatiles.s
;
; file generated by tools/generateMetatiles.c
; contains metatile definitions
; order: t1 t2 b1 b2
;

.EXPORT metatiles

metatiles:
	.WORD tile_0, tile_1, tile_2, tile_3, tile_4

tile_0:
	.BYTE $00, $00, $00, $00 
	.BYTE $00, $00, $00, $00 

tile_1:
	.BYTE $01, $02, $11, $12 
	.BYTE $01, $01, $01, $01 

tile_2:
	.BYTE $00, $00, $03, $03 
	.BYTE $00, $00, $01, $01 

tile_3:
	.BYTE $03, $00, $03, $00 
	.BYTE $01, $00, $01, $00 

tile_4:
	.BYTE $04, $04, $04, $04 
	.BYTE $00, $00, $00, $00 