;
; neschael
; data/levels/****.s
;
; file generated by tools/formatSong.c
; music and sfx data
;

song_list:
	.WORD _emegamahb
	.WORD _Newsong3

sfx_list:

instrument_list:
	.WORD _MultiTasker_0
	.WORD _Tick_1
	.WORD _Snare_2
	.WORD _Hat_3
	.WORD _Twinkle_4
	.WORD _Silent_5
; order: vol, pitch, duty, arp

_MultiTasker_0:
	.BYTE $05, $08, $0A, $0C, $00
	.BYTE $00, $0F, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Tick_1:
	.BYTE $05, $09, $0B, $0D, $00
	.BYTE $00, $0F, $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Snare_2:
	.BYTE $05, $0D, $0F, $11, $00
	.BYTE $0F, $0F, $0E, $07, $05, $03, $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE $00, $06, $06, $06, $07, $08, ENV_STOP

_Hat_3:
	.BYTE $05, $0A, $0C, $0E, $00
	.BYTE $0F, $09, $07, $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Twinkle_4:
	.BYTE $05, $0B, $0D, $0F, $00
	.BYTE $0F, $0F, $07, $07, $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

_Silent_5:
	.BYTE $05, $07, $09, $0B, $00
	.BYTE $00, ENV_STOP
	.BYTE $00, ENV_STOP
	.BYTE $00, DUTY_ENV_STOP
	.BYTE ENV_STOP

