;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT intestines_1

intestines_1:
	.WORD background_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $07 ; ammount of backgrounds, zero based
	.BYTE $3F ; background color
	.BYTE $00, $01, $02, $03 ; background palettes
	.BYTE $04, $01, $02, $03 ; sprite palettes
  .BYTE $00 ; music ID
  
background_index:
	.WORD background_0, background_1, background_2, background_3, background_4, background_5, background_6, background_7
spawn_stream:
	.WORD stream_0,stream_1,stream_2,stream_3,stream_4,stream_5,stream_6,stream_7

background_0:
  .BYTE $FF, $01, $0D, $00, $FF, $00, $08, $0E, $0B, $0C, $30, $16, $FF, $05, $0A, $47 
  .BYTE $03, $52, $08, $54, $04, $5D, $07, $60, $05, $68, $06, $6C, $06, $73, $05, $78 
  .BYTE $07, $7E, $04, $84, $08, $89, $03, $90, $08, $5D, $03, $A1, $04, $52, $FF, $02 
  .BYTE $07, $A3, $04, $A2, $06, $AE, $FC, $00, $F0, $FF, $0F, $03, $BC, $FD, $30, $33 
  .BYTE $03, $08, $55, $FC, $55, $55, $55, $05, $06, $D0, $FE, $C0, $0C, $04, $D8, $FE 
  .BYTE $F0, $0F, $04, $DE, $FE, $30, $03, $06, $D2, $FE, $00, $00, $00 

stream_0:

background_1:
  .BYTE $FB, $01, $00, $02, $00, $00, $04, $01, $FD, $02, $00, $01, $04, $00, $04, $0E 
  .BYTE $3D, $08, $FF, $01, $40, $46, $04, $43, $0C, $8A, $03, $A1, $04, $99, $09, $A8 
  .BYTE $06, $9A, $07, $B7, $FC, $01, $11, $11, $11, $0B, $B4, $07, $CD, $FD, $44, $44 
  .BYTE $44, $03, $D2, $FD, $55, $55, $55, $0F, $D8, $03, $EC, $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00

background_2:
  .BYTE $FE, $01, $00, $09, $01, $0B, $00, $5E, $0A, $FE, $01, $01, $22, $6A, $07, $68 
  .BYTE $FF, $01, $03, $9F, $09, $97, $05, $9D, $09, $A5, $0D, $66, $FE, $50, $55, $0D 
  .BYTE $C3, $FE, $A0, $AA, $04, $CF, $08, $D6, $F8, $C0, $CC, $00, $00, $20, $22, $F0 
  .BYTE $FF, $06, $BA, $00 

stream_2:
	.BYTE $48, $00, $00 ; X: 08, Y: 04
	.BYTE $00

background_3:
  .BYTE $FC, $00, $00, $00, $01, $03, $00, $04, $06, $04, $03, $19, $03, $FF, $01, $04 
  .BYTE $26, $07, $19, $FF, $01, $03, $34, $09, $18, $05, $36, $08, $2E, $0C, $1E, $03 
  .BYTE $59, $FE, $04, $04, $0A, $37, $14, $5D, $FE, $03, $03, $15, $67, $0B, $58, $FF 
  .BYTE $03, $0A, $94, $FE, $03, $03, $0A, $4C, $03, $7E, $07, $35, $FE, $F0, $FF, $07 
  .BYTE $1C, $04, $C8, $FD, $A0, $AA, $AA, $09, $CA, $FD, $20, $22, $22, $0B, $C2, $03 
  .BYTE $E6, $FF, $FF, $05, $EA, $FE, $0C, $00, $00 

stream_3:
	.BYTE $52, $00, $00 ; X: 02, Y: 05
	.BYTE $B3, $00, $00 ; X: 03, Y: 11
	.BYTE $00

background_4:
  .BYTE $F8, $00, $00, $03, $0A, $0A, $00, $00, $01, $04, $07, $FF, $00, $03, $0C, $03 
  .BYTE $04, $03, $12, $07, $0A, $05, $10, $06, $16, $05, $0F, $07, $09, $05, $1B, $FF 
  .BYTE $01, $03, $38, $07, $30, $03, $2E, $07, $3B, $FE, $00, $0A, $03, $47, $07, $2F 
  .BYTE $FF, $03, $08, $4F, $FE, $0A, $0A, $0B, $59, $03, $00, $04, $6A, $06, $5F, $06 
  .BYTE $20, $07, $0B, $05, $2E, $07, $17, $05, $8F, $04, $96, $FF, $03, $05, $9F, $08 
  .BYTE $51, $FE, $01, $0A, $07, $A3, $05, $07, $06, $35, $2F, $C0, $FE, $08, $00, $00 

stream_4:
	.BYTE $63, $00, $00 ; X: 03, Y: 06
	.BYTE $00

background_5:
  .BYTE $FC, $00, $00, $01, $00, $07, $03, $03, $02, $FF, $01, $04, $0B, $07, $07, $03 
  .BYTE $0D, $04, $0E, $0B, $00, $9F, $20, $25, $CA, $FE, $01, $00, $00 

stream_5:
	.BYTE $80, $00, $00 ; X: 00, Y: 08
	.BYTE $00

background_6:
  .BYTE $FF, $00, $0A, $00, $FF, $01, $BF, $00, $25, $CA, $FE, $01, $00, $00 

stream_6:
	.BYTE $30, $00, $00 ; X: 00, Y: 03
	.BYTE $00

background_7:
  .BYTE $FF, $00, $0A, $00, $FF, $01, $BF, $00, $25, $CA, $FE, $08, $00, $00 

stream_7:
	.BYTE $73, $00, $00 ; X: 03, Y: 07
	.BYTE $00
