;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT mouth_level

mouth_level:
	.WORD background_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $01 ; length of background, zero based

background_index:
	.WORD background_0, background_1
spawn_stream:
	.WORD stream_0,stream_1

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $07, $0C, $FF, $06, $0B, $09, $04, $13, $09, $18 
  .BYTE $03, $20, $0A, $24, $FF, $00, $3B, $2F, $FF, $07, $0B, $6B, $FF, $08, $0A, $77 
  .BYTE $FF, $07, $0B, $22, $FF, $08, $0A, $8E, $03, $8D, $09, $9B, $03, $99, $08, $A7 
  .BYTE $04, $A4, $FB, $01, $00, $F0, $FF, $0F, $03, $B8, $FD, $30, $33, $03, $08, $A8 
  .BYTE $FC, $55, $55, $55, $05, $06, $D0, $FE, $C0, $0C, $04, $D8, $FE, $F0, $0F, $04 
  .BYTE $DE, $FE, $30, $03, $06, $D2, $FE, $00, $00, $00 

stream_0:

background_1:
  .BYTE $FF, $00, $06, $00, $FE, $08, $01, $03, $08, $07, $00, $04, $08, $14, $0B, $05 
  .BYTE $1B, $0A, $25, $FF, $05, $0A, $2F, $FF, $05, $0A, $22, $03, $45, $08, $47, $04 
  .BYTE $50, $05, $53, $06, $5E, $FE, $02, $01, $06, $1E, $04, $65, $FF, $02, $04, $70 
  .BYTE $05, $76, $06, $1D, $05, $80, $0E, $7F, $06, $6D, $04, $9E, $FD, $04, $04, $0C 
  .BYTE $15, $9A, $04, $94, $FC, $01, $11, $11, $11, $0C, $23, $06, $CE, $FD, $44, $44 
  .BYTE $44, $03, $D2, $FD, $55, $55, $55, $09, $D8, $FE, $15, $51, $04, $E3, $03, $EC 
  .BYTE $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00
