;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT mouth_level

mouth_level:
	.WORD background_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $01 ; length of background, zero based
  .BYTE $21 ; background color
	.BYTE $05, $01, $02, $03 ; background palettes
	.BYTE $04, $01, $02, $03 ; sprite palettes

background_index:
	.WORD background_0, background_1
spawn_stream:
	.WORD stream_0,stream_1

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $07, $0C, $FF, $06, $0B, $09, $04, $13, $09, $18 
  .BYTE $FE, $00, $0D, $5F, $23, $FE, $06, $0D, $0A, $84, $FF, $00, $30, $8F, $27, $CA 
	.BYTE $00

stream_0:

background_1:
  .BYTE $FF, $00, $0A, $00, $FF, $0D, $0A, $01, $FF, $0F, $0B, $0B, $FF, $02, $0B, $17 
  .BYTE $FF, $0E, $0A, $23, $FF, $02, $0B, $0A, $FF, $08, $0B, $3A, $FF, $0E, $12, $46 
  .BYTE $FE, $01, $01, $07, $5A, $FF, $01, $05, $6D, $05, $67, $03, $71, $FF, $02, $04 
  .BYTE $70, $03, $7B, $04, $77, $04, $6C, $FD, $00, $00, $0B, $06, $6F, $0A, $88, $05 
  .BYTE $9D, $FE, $04, $04, $16, $99, $07, $6E, $FC, $00, $00, $40, $04, $04, $C0, $FE 
  .BYTE $54, $05, $03, $C7, $FE, $50, $55, $03, $CB, $FB, $50, $55, $55, $05, $55, $04 
  .BYTE $D8, $06, $D7, $FF, $45, $05, $DE, $07, $E8, $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00
