;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT test_level_2

test_level_2:
	.WORD background_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $07 ; length of background, zero based
	.BYTE $3F ; background color
	.BYTE $00, $01, $02, $03 ; background palettes
	.BYTE $04, $01, $02, $03 ; sprite palettes
  
background_index:
	.WORD background_0, background_1, background_2, background_3, background_4, background_5, background_6, background_7
spawn_stream:
	.WORD stream_0,stream_1,stream_2,stream_3,stream_4,stream_5,stream_6,stream_7

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $06, $0C, $FF, $06, $0B, $08, $05, $12, $06, $1A 
  .BYTE $FF, $02, $05, $1E, $06, $24, $FF, $03, $05, $1D, $06, $25, $04, $36, $FF, $00 
  .BYTE $07, $3B, $05, $48, $05, $47, $06, $41, $07, $52, $06, $30, $05, $5F, $FF, $08 
  .BYTE $0B, $65, $07, $2F, $09, $17, $03, $81, $0B, $5F, $04, $8E, $FE, $02, $01, $06 
  .BYTE $94, $FF, $09, $0B, $9B, $FF, $0A, $05, $8E, $09, $64, $FD, $F0, $FF, $0F, $03 
  .BYTE $BC, $FE, $30, $33, $06, $59, $03, $CE, $FC, $55, $55, $55, $05, $06, $D0, $FE 
  .BYTE $C0, $0C, $04, $D8, $FE, $F0, $0F, $04, $DE, $FE, $30, $03, $06, $D2, $FE, $00 
  .BYTE $00, $00 

stream_0:

background_1:
  .BYTE $FB, $01, $00, $00, $00, $02, $03, $01, $03, $07, $FF, $01, $03, $00, $FF, $02 
  .BYTE $04, $00, $56, $08, $FF, $01, $1C, $5F, $07, $86, $32, $82, $FD, $11, $11, $11 
  .BYTE $0A, $B4, $08, $CC, $FD, $44, $44, $44, $03, $D2, $FD, $55, $55, $55, $0F, $D8 
  .BYTE $03, $EC, $FE, $28, $08, $00 

stream_1:
	.BYTE $93, $00, $00 ; X: 03, Y: 09
	.BYTE $85, $00, $00 ; X: 05, Y: 08
	.BYTE $4B, $00, $00 ; X: 11, Y: 04
	.BYTE $00

background_2:
  .BYTE $FE, $01, $00, $08, $01, $FE, $01, $01, $14, $00, $03, $16, $05, $22, $08, $1C 
  .BYTE $FD, $00, $04, $04, $07, $18, $FF, $06, $0B, $2F, $FF, $00, $04, $3F, $0C, $3F 
  .BYTE $09, $0E, $1C, $54, $07, $6B, $23, $6B, $FF, $07, $0B, $8F, $FF, $08, $0A, $9B 
  .BYTE $FF, $07, $09, $17, $FE, $50, $55, $0D, $C3, $FE, $A0, $AA, $04, $CF, $08, $D6 
  .BYTE $F8, $C0, $CC, $00, $00, $20, $22, $F0, $FF, $06, $96, $00 

stream_2:
	.BYTE $48, $00, $00 ; X: 08, Y: 04
	.BYTE $00

background_3:
  .BYTE $FF, $00, $03, $00, $FF, $01, $04, $00, $FE, $08, $01, $05, $04, $05, $0F, $FF 
  .BYTE $01, $13, $0A, $04, $23, $38, $21, $04, $64, $FF, $09, $0B, $5E, $FF, $0A, $0B 
  .BYTE $6A, $03, $68, $0A, $78, $FF, $0A, $0B, $83, $06, $03, $12, $94, $FF, $07, $0B 
  .BYTE $A7, $FC, $08, $01, $F0, $FF, $0B, $9C, $FD, $A0, $AA, $AA, $09, $CA, $FD, $20 
  .BYTE $22, $22, $0B, $C2, $03, $E6, $FF, $FF, $05, $EA, $FE, $0C, $00, $00 

stream_3:
	.BYTE $52, $00, $00 ; X: 02, Y: 05
	.BYTE $B3, $00, $00 ; X: 03, Y: 11
	.BYTE $00

background_4:
  .BYTE $FF, $00, $08, $00, $FD, $07, $01, $01, $09, $00, $FF, $08, $0B, $0A, $FF, $01 
  .BYTE $0B, $16, $03, $1F, $22, $24, $0C, $22, $30, $52, $06, $46, $07, $83, $23, $8F 
  .BYTE $FF, $07, $0C, $83, $25, $CA, $FE, $08, $00, $00 

stream_4:
	.BYTE $63, $00, $00 ; X: 03, Y: 06
	.BYTE $00

background_5:
  .BYTE $FF, $00, $03, $00, $FF, $01, $04, $00, $FE, $00, $02, $05, $04, $1E, $04, $FF 
  .BYTE $0A, $06, $28, $06, $34, $46, $2F, $FF, $0E, $2F, $76, $FF, $08, $09, $A6, $FF 
  .BYTE $01, $05, $BA, $2F, $C0, $FE, $01, $00, $00 

stream_5:
	.BYTE $80, $00, $00 ; X: 00, Y: 08
	.BYTE $00

background_6:
  .BYTE $FF, $00, $06, $00, $FF, $01, $05, $06, $29, $01, $FF, $01, $0B, $2B, $FF, $09 
  .BYTE $04, $3B, $07, $3B, $FF, $0A, $0B, $43, $05, $52, $0D, $53, $08, $2F, $16, $68 
  .BYTE $05, $83, $08, $83, $09, $86, $0D, $9A, $09, $30, $0A, $AA, $0A, $B5, $26, $C9 
  .BYTE $FE, $01, $00, $00 

stream_6:
	.BYTE $30, $00, $00 ; X: 00, Y: 03
	.BYTE $00

background_7:
  .BYTE $FE, $01, $00, $08, $01, $FE, $05, $01, $09, $00, $03, $0A, $08, $0C, $04, $15 
  .BYTE $08, $18, $04, $21, $0A, $00, $03, $2B, $0E, $31, $0A, $24, $32, $49, $18, $33 
  .BYTE $16, $93, $0B, $B4, $0A, $A9, $26, $C9, $FE, $08, $00, $00 

stream_7:
	.BYTE $73, $00, $00 ; X: 03, Y: 07
	.BYTE $00
