;
; neschael
; data/levels/****.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT test_level_2

test_level_2:
	.WORD background_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $07 ; length of background, zero based
	.BYTE $3F ; background color
	.BYTE $00, $01, $02, $03 ; background palettes
	.BYTE $04, $01, $02, $03 ; sprite palettes
  .BYTE $00 ; music ID
  
background_index:
	.WORD background_0, background_1, background_2, background_3, background_4, background_5, background_6, background_7
spawn_stream:
	.WORD stream_0,stream_1,stream_2,stream_3,stream_4,stream_5,stream_6,stream_7

background_0:
  .BYTE $FF, $01, $0B, $00, $FF, $00, $07, $0C, $0C, $08, $04, $13, $09, $18, $03, $20 
  .BYTE $0A, $24, $FF, $00, $41, $2F, $07, $6B, $17, $23, $05, $8E, $08, $8F, $0D, $9B 
  .BYTE $0C, $8F, $0B, $6C, $25, $CA, $FE, $80, $FF, $00 

stream_0:
	.BYTE $A7, $00, $00 ; X: 07, Y: 10
	.BYTE $A8, $00, $00 ; X: 08, Y: 10
	.BYTE $A9, $00, $00 ; X: 09, Y: 10
	.BYTE $AA, $00, $00 ; X: 10, Y: 10
	.BYTE $AB, $00, $00 ; X: 11, Y: 10
	.BYTE $AC, $00, $00 ; X: 12, Y: 10
	.BYTE $AD, $00, $00 ; X: 13, Y: 10
	.BYTE $AE, $00, $00 ; X: 14, Y: 10
	.BYTE $AF, $00, $00 ; X: 15, Y: 10
	.BYTE $00

background_1:
  .BYTE $FE, $01, $00, $09, $01, $FF, $01, $04, $00, $07, $00, $53, $0B, $FF, $01, $1D 
  .BYTE $5F, $08, $59, $30, $84, $0A, $01, $26, $C9, $FE, $0F, $10, $00 

stream_1:
	.BYTE $A0, $00, $00 ; X: 00, Y: 10
	.BYTE $A1, $00, $00 ; X: 01, Y: 10
	.BYTE $A2, $00, $00 ; X: 02, Y: 10
	.BYTE $A3, $00, $00 ; X: 03, Y: 10
	.BYTE $4C, $00, $00 ; X: 12, Y: 04
	.BYTE $00

background_2:
  .BYTE $FE, $01, $00, $08, $01, $FE, $01, $01, $14, $00, $03, $16, $05, $22, $08, $1C 
  .BYTE $04, $29, $08, $19, $1B, $30, $09, $0E, $5E, $54, $0B, $0B, $29, $C8, $00 

stream_2:

background_3:
  .BYTE $FF, $00, $09, $00, $FE, $01, $01, $0B, $01, $52, $0B, $0C, $09, $0D, $69, $FF 
  .BYTE $00, $17, $77, $30, $3A, $26, $C9, $FE, $01, $00, $00 

stream_3:
	.BYTE $70, $00, $00 ; X: 00, Y: 07
	.BYTE $00

background_4:
  .BYTE $FF, $00, $07, $00, $FF, $01, $03, $08, $5B, $00, $04, $5C, $14, $5F, $05, $71 
  .BYTE $45, $78, $28, $C8, $FF, $02, $00 

stream_4:
	.BYTE $69, $00, $00 ; X: 09, Y: 06
	.BYTE $00

background_5:
  .BYTE $FF, $00, $08, $00, $FD, $01, $01, $01, $15, $00, $03, $13, $0B, $19, $23, $23 
  .BYTE $0C, $22, $18, $52, $17, $3A, $17, $09, $03, $99, $14, $9B, $04, $B1, $0C, $5F 
  .BYTE $26, $CA, $FF, $01, $00 

stream_5:
	.BYTE $A8, $00, $00 ; X: 08, Y: 10
	.BYTE $00

background_6:
  .BYTE $FF, $00, $06, $00, $FB, $01, $01, $01, $00, $01, $14, $00, $05, $1E, $11, $19 
  .BYTE $05, $14, $0A, $23, $06, $41, $21, $3F, $08, $2F, $16, $68, $05, $83, $08, $83 
  .BYTE $09, $86, $0D, $9A, $09, $30, $0A, $AA, $0A, $B5, $27, $C9, $FF, $01, $00 

stream_6:
	.BYTE $58, $00, $00 ; X: 08, Y: 05
	.BYTE $00

background_7:
  .BYTE $FE, $01, $00, $08, $01, $FE, $05, $01, $09, $00, $03, $0A, $08, $0C, $04, $15 
  .BYTE $08, $18, $04, $21, $0A, $00, $03, $2B, $0E, $31, $0A, $24, $2C, $49, $FE, $04 
  .BYTE $04, $0A, $3B, $0C, $81, $12, $39, $0A, $9F, $0B, $B4, $0A, $A9, $26, $C9, $FE 
  .BYTE $08, $00, $00 

stream_7:
	.BYTE $83, $00, $00 ; X: 03, Y: 08
	.BYTE $00
