;
; neschael
; data/levels/testLevel5.s
;
; file generated by tools/formatCanvas.c
; contains level data
;

.EXPORT test_level_5

test_level_5:
	.WORD background_index, attribute_index, spawn_stream
	.BYTE $30, $8F ; high byte of player starting X and Y
	.BYTE $04 ; length of background, zero based

background_index:
	.WORD background_0, background_1, background_2, background_3
attribute_index:
	.WORD attrib_0, attrib_1, attrib_2, attrib_3
spawn_stream:
	.WORD stream_0,stream_1,stream_2,stream_3

background_0:
  .BYTE $FF, $00, $07, $00, $FE, $02, $01, $03, $09, $08, $00, $FC, $00, $02, $00, $00 
  .BYTE $07, $0C, $03, $16, $09, $16, $FE, $02, $03, $0C, $21, $0C, $13, $0B, $39, $FE 
  .BYTE $03, $03, $03, $2D, $04, $55, $0A, $0C, $14, $57, $07, $46, $09, $72, $FF, $02 
  .BYTE $0C, $7C, $05, $49, $05, $0B, $0C, $78, $0A, $0B, $10, $A8, $0A, $6B, $FF, $01, $00

attrib_0:
  .BYTE $FF, $00, $22, $00, $FF, $03, $06, $22, $FF, $0F, $06, $29, $07, $30, $FF, $00 
  .BYTE $06, $37, $91, $3E, $00

stream_0:
	; todo :)

background_1:
  .BYTE $FC, $00, $00, $02, $00, $07, $03, $FB, $01, $01, $01, $00, $02, $03, $0C, $1D 
  .BYTE $06, $03, $29, $10, $26, $03, $23, $11, $39, $07, $22, $15, $51, $04, $4A, $0C 
  .BYTE $6A, $0A, $4F, $09, $1C, $0F, $89, $FF, $02, $06, $49, $06, $4C, $03, $02, $FE 
  .BYTE $01, $03, $04, $B6, $08, $AE, $06, $62, $07, $BC, $00

attrib_1:
  .BYTE $FE, $00, $0F, $05, $00, $A9, $06, $FD, $41, $05, $02, $1D, $93, $00

stream_1:
	; todo :)

background_2:
  .BYTE $FF, $00, $08, $00, $FF, $01, $03, $09, $09, $00, $04, $06, $09, $15, $07, $1B 
  .BYTE $FF, $02, $07, $1E, $05, $0B, $08, $2A, $0D, $25, $1A, $3F, $06, $0B, $0D, $5F 
  .BYTE $09, $02, $12, $75, $07, $8E, $0B, $8E, $FF, $02, $26, $9A, $03, $0A, $00

attrib_2:
  .BYTE $FF, $00, $77, $00, $FD, $41, $05, $02, $55, $23, $00

stream_2:
	; todo :)

background_3:
  .BYTE $FF, $00, $04, $00, $FF, $01, $05, $01, $FF, $01, $05, $05, $03, $09, $18, $07 
  .BYTE $05, $04, $16, $24, $04, $46, $FF, $02, $0B, $3F, $FF, $02, $0F, $4B, $0B, $41 
  .BYTE $0E, $65, $0A, $74, $0E, $7D, $0B, $73, $1D, $96, $08, $B2, $FF, $04, $03, $C8 
  .BYTE $04, $BF, $00

attrib_3:
  .BYTE $FF, $00, $3F, $00, $FD, $41, $05, $02, $40, $00, $4D, $82, $00

stream_3:
	; todo :)
